vars:
  region: us-west-2
  sourceName: avinci/node_app
  integration: avinci_dh
  branches:
    master:
      sourceName: avinci/node_app_master
    feat:
      sourceName: avinci/node_app_feat

login_image_registry_temp: &login_image_registry
  - |
      # login to docker hub
      IMAGE_NAME=$(shipctl get_resource_version_key "$image_res" "sourceName")
      DH_USR_NAME=$(shipctl get_integration_resource_field "$image_res" "userName")
      DH_PASS=$(shipctl get_integration_resource_field "$image_res" "password")
      DH_URL=$(shipctl get_integration_resource_field "$image_res" "url")
      docker login -u $DH_USR_NAME -p $DH_PASS

resources:
  - name: temp_img
    type: image
    integration: ${integration}
    versionTemplate:
      sourceName: ${sourceName}
      versionName: "latest"
      region: ${region}

jobs:
  - name: test_vars
    type: runSh
    steps:
      - IN: temp_img
      - TASK:
          name: test_img
          runtime:
            options:
              env:
                - image_res: "temp_img"
          script:
            - *login_image_registry
            - echo $IMAGE_NAME
